// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvoiceAppAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class InvoiceAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvoiceAppAPI.Entity.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("IdentityCard")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            IdentityCard = "IC001",
                            Name = "Customer 1"
                        },
                        new
                        {
                            CustomerId = 2,
                            IdentityCard = "IC002",
                            Name = "Customer 2"
                        },
                        new
                        {
                            CustomerId = 3,
                            IdentityCard = "IC003",
                            Name = "Customer 3"
                        },
                        new
                        {
                            CustomerId = 4,
                            IdentityCard = "IC004",
                            Name = "Customer 4"
                        },
                        new
                        {
                            CustomerId = 5,
                            IdentityCard = "IC005",
                            Name = "Customer 5"
                        },
                        new
                        {
                            CustomerId = 6,
                            IdentityCard = "IC006",
                            Name = "Customer 6"
                        },
                        new
                        {
                            CustomerId = 7,
                            IdentityCard = "IC007",
                            Name = "Customer 7"
                        },
                        new
                        {
                            CustomerId = 8,
                            IdentityCard = "IC008",
                            Name = "Customer 8"
                        },
                        new
                        {
                            CustomerId = 9,
                            IdentityCard = "IC009",
                            Name = "Customer 9"
                        },
                        new
                        {
                            CustomerId = 10,
                            IdentityCard = "IC0010",
                            Name = "Customer 10"
                        },
                        new
                        {
                            CustomerId = 11,
                            IdentityCard = "IC0011",
                            Name = "Customer 11"
                        },
                        new
                        {
                            CustomerId = 12,
                            IdentityCard = "IC0012",
                            Name = "Customer 12"
                        },
                        new
                        {
                            CustomerId = 13,
                            IdentityCard = "IC0013",
                            Name = "Customer 13"
                        },
                        new
                        {
                            CustomerId = 14,
                            IdentityCard = "IC0014",
                            Name = "Customer 14"
                        },
                        new
                        {
                            CustomerId = 15,
                            IdentityCard = "IC0015",
                            Name = "Customer 15"
                        },
                        new
                        {
                            CustomerId = 16,
                            IdentityCard = "IC0016",
                            Name = "Customer 16"
                        },
                        new
                        {
                            CustomerId = 17,
                            IdentityCard = "IC0017",
                            Name = "Customer 17"
                        },
                        new
                        {
                            CustomerId = 18,
                            IdentityCard = "IC0018",
                            Name = "Customer 18"
                        },
                        new
                        {
                            CustomerId = 19,
                            IdentityCard = "IC0019",
                            Name = "Customer 19"
                        },
                        new
                        {
                            CustomerId = 20,
                            IdentityCard = "IC0020",
                            Name = "Customer 20"
                        },
                        new
                        {
                            CustomerId = 21,
                            IdentityCard = "IC0021",
                            Name = "Customer 21"
                        },
                        new
                        {
                            CustomerId = 22,
                            IdentityCard = "IC0022",
                            Name = "Customer 22"
                        },
                        new
                        {
                            CustomerId = 23,
                            IdentityCard = "IC0023",
                            Name = "Customer 23"
                        },
                        new
                        {
                            CustomerId = 24,
                            IdentityCard = "IC0024",
                            Name = "Customer 24"
                        },
                        new
                        {
                            CustomerId = 25,
                            IdentityCard = "IC0025",
                            Name = "Customer 25"
                        },
                        new
                        {
                            CustomerId = 26,
                            IdentityCard = "IC0026",
                            Name = "Customer 26"
                        },
                        new
                        {
                            CustomerId = 27,
                            IdentityCard = "IC0027",
                            Name = "Customer 27"
                        },
                        new
                        {
                            CustomerId = 28,
                            IdentityCard = "IC0028",
                            Name = "Customer 28"
                        },
                        new
                        {
                            CustomerId = 29,
                            IdentityCard = "IC0029",
                            Name = "Customer 29"
                        },
                        new
                        {
                            CustomerId = 30,
                            IdentityCard = "IC0030",
                            Name = "Customer 30"
                        },
                        new
                        {
                            CustomerId = 31,
                            IdentityCard = "IC0031",
                            Name = "Customer 31"
                        },
                        new
                        {
                            CustomerId = 32,
                            IdentityCard = "IC0032",
                            Name = "Customer 32"
                        },
                        new
                        {
                            CustomerId = 33,
                            IdentityCard = "IC0033",
                            Name = "Customer 33"
                        },
                        new
                        {
                            CustomerId = 34,
                            IdentityCard = "IC0034",
                            Name = "Customer 34"
                        },
                        new
                        {
                            CustomerId = 35,
                            IdentityCard = "IC0035",
                            Name = "Customer 35"
                        },
                        new
                        {
                            CustomerId = 36,
                            IdentityCard = "IC0036",
                            Name = "Customer 36"
                        },
                        new
                        {
                            CustomerId = 37,
                            IdentityCard = "IC0037",
                            Name = "Customer 37"
                        },
                        new
                        {
                            CustomerId = 38,
                            IdentityCard = "IC0038",
                            Name = "Customer 38"
                        },
                        new
                        {
                            CustomerId = 39,
                            IdentityCard = "IC0039",
                            Name = "Customer 39"
                        },
                        new
                        {
                            CustomerId = 40,
                            IdentityCard = "IC0040",
                            Name = "Customer 40"
                        },
                        new
                        {
                            CustomerId = 41,
                            IdentityCard = "IC0041",
                            Name = "Customer 41"
                        },
                        new
                        {
                            CustomerId = 42,
                            IdentityCard = "IC0042",
                            Name = "Customer 42"
                        },
                        new
                        {
                            CustomerId = 43,
                            IdentityCard = "IC0043",
                            Name = "Customer 43"
                        },
                        new
                        {
                            CustomerId = 44,
                            IdentityCard = "IC0044",
                            Name = "Customer 44"
                        },
                        new
                        {
                            CustomerId = 45,
                            IdentityCard = "IC0045",
                            Name = "Customer 45"
                        },
                        new
                        {
                            CustomerId = 46,
                            IdentityCard = "IC0046",
                            Name = "Customer 46"
                        },
                        new
                        {
                            CustomerId = 47,
                            IdentityCard = "IC0047",
                            Name = "Customer 47"
                        },
                        new
                        {
                            CustomerId = 48,
                            IdentityCard = "IC0048",
                            Name = "Customer 48"
                        },
                        new
                        {
                            CustomerId = 49,
                            IdentityCard = "IC0049",
                            Name = "Customer 49"
                        },
                        new
                        {
                            CustomerId = 50,
                            IdentityCard = "IC0050",
                            Name = "Customer 50"
                        },
                        new
                        {
                            CustomerId = 51,
                            IdentityCard = "IC0051",
                            Name = "Customer 51"
                        },
                        new
                        {
                            CustomerId = 52,
                            IdentityCard = "IC0052",
                            Name = "Customer 52"
                        },
                        new
                        {
                            CustomerId = 53,
                            IdentityCard = "IC0053",
                            Name = "Customer 53"
                        },
                        new
                        {
                            CustomerId = 54,
                            IdentityCard = "IC0054",
                            Name = "Customer 54"
                        },
                        new
                        {
                            CustomerId = 55,
                            IdentityCard = "IC0055",
                            Name = "Customer 55"
                        },
                        new
                        {
                            CustomerId = 56,
                            IdentityCard = "IC0056",
                            Name = "Customer 56"
                        },
                        new
                        {
                            CustomerId = 57,
                            IdentityCard = "IC0057",
                            Name = "Customer 57"
                        },
                        new
                        {
                            CustomerId = 58,
                            IdentityCard = "IC0058",
                            Name = "Customer 58"
                        },
                        new
                        {
                            CustomerId = 59,
                            IdentityCard = "IC0059",
                            Name = "Customer 59"
                        },
                        new
                        {
                            CustomerId = 60,
                            IdentityCard = "IC0060",
                            Name = "Customer 60"
                        },
                        new
                        {
                            CustomerId = 61,
                            IdentityCard = "IC0061",
                            Name = "Customer 61"
                        },
                        new
                        {
                            CustomerId = 62,
                            IdentityCard = "IC0062",
                            Name = "Customer 62"
                        },
                        new
                        {
                            CustomerId = 63,
                            IdentityCard = "IC0063",
                            Name = "Customer 63"
                        },
                        new
                        {
                            CustomerId = 64,
                            IdentityCard = "IC0064",
                            Name = "Customer 64"
                        },
                        new
                        {
                            CustomerId = 65,
                            IdentityCard = "IC0065",
                            Name = "Customer 65"
                        },
                        new
                        {
                            CustomerId = 66,
                            IdentityCard = "IC0066",
                            Name = "Customer 66"
                        },
                        new
                        {
                            CustomerId = 67,
                            IdentityCard = "IC0067",
                            Name = "Customer 67"
                        },
                        new
                        {
                            CustomerId = 68,
                            IdentityCard = "IC0068",
                            Name = "Customer 68"
                        },
                        new
                        {
                            CustomerId = 69,
                            IdentityCard = "IC0069",
                            Name = "Customer 69"
                        },
                        new
                        {
                            CustomerId = 70,
                            IdentityCard = "IC0070",
                            Name = "Customer 70"
                        },
                        new
                        {
                            CustomerId = 71,
                            IdentityCard = "IC0071",
                            Name = "Customer 71"
                        },
                        new
                        {
                            CustomerId = 72,
                            IdentityCard = "IC0072",
                            Name = "Customer 72"
                        },
                        new
                        {
                            CustomerId = 73,
                            IdentityCard = "IC0073",
                            Name = "Customer 73"
                        },
                        new
                        {
                            CustomerId = 74,
                            IdentityCard = "IC0074",
                            Name = "Customer 74"
                        },
                        new
                        {
                            CustomerId = 75,
                            IdentityCard = "IC0075",
                            Name = "Customer 75"
                        },
                        new
                        {
                            CustomerId = 76,
                            IdentityCard = "IC0076",
                            Name = "Customer 76"
                        },
                        new
                        {
                            CustomerId = 77,
                            IdentityCard = "IC0077",
                            Name = "Customer 77"
                        },
                        new
                        {
                            CustomerId = 78,
                            IdentityCard = "IC0078",
                            Name = "Customer 78"
                        },
                        new
                        {
                            CustomerId = 79,
                            IdentityCard = "IC0079",
                            Name = "Customer 79"
                        },
                        new
                        {
                            CustomerId = 80,
                            IdentityCard = "IC0080",
                            Name = "Customer 80"
                        },
                        new
                        {
                            CustomerId = 81,
                            IdentityCard = "IC0081",
                            Name = "Customer 81"
                        },
                        new
                        {
                            CustomerId = 82,
                            IdentityCard = "IC0082",
                            Name = "Customer 82"
                        },
                        new
                        {
                            CustomerId = 83,
                            IdentityCard = "IC0083",
                            Name = "Customer 83"
                        },
                        new
                        {
                            CustomerId = 84,
                            IdentityCard = "IC0084",
                            Name = "Customer 84"
                        },
                        new
                        {
                            CustomerId = 85,
                            IdentityCard = "IC0085",
                            Name = "Customer 85"
                        },
                        new
                        {
                            CustomerId = 86,
                            IdentityCard = "IC0086",
                            Name = "Customer 86"
                        },
                        new
                        {
                            CustomerId = 87,
                            IdentityCard = "IC0087",
                            Name = "Customer 87"
                        },
                        new
                        {
                            CustomerId = 88,
                            IdentityCard = "IC0088",
                            Name = "Customer 88"
                        },
                        new
                        {
                            CustomerId = 89,
                            IdentityCard = "IC0089",
                            Name = "Customer 89"
                        },
                        new
                        {
                            CustomerId = 90,
                            IdentityCard = "IC0090",
                            Name = "Customer 90"
                        },
                        new
                        {
                            CustomerId = 91,
                            IdentityCard = "IC0091",
                            Name = "Customer 91"
                        },
                        new
                        {
                            CustomerId = 92,
                            IdentityCard = "IC0092",
                            Name = "Customer 92"
                        },
                        new
                        {
                            CustomerId = 93,
                            IdentityCard = "IC0093",
                            Name = "Customer 93"
                        },
                        new
                        {
                            CustomerId = 94,
                            IdentityCard = "IC0094",
                            Name = "Customer 94"
                        },
                        new
                        {
                            CustomerId = 95,
                            IdentityCard = "IC0095",
                            Name = "Customer 95"
                        },
                        new
                        {
                            CustomerId = 96,
                            IdentityCard = "IC0096",
                            Name = "Customer 96"
                        },
                        new
                        {
                            CustomerId = 97,
                            IdentityCard = "IC0097",
                            Name = "Customer 97"
                        },
                        new
                        {
                            CustomerId = 98,
                            IdentityCard = "IC0098",
                            Name = "Customer 98"
                        },
                        new
                        {
                            CustomerId = 99,
                            IdentityCard = "IC0099",
                            Name = "Customer 99"
                        },
                        new
                        {
                            CustomerId = 100,
                            IdentityCard = "IC00100",
                            Name = "Customer 100"
                        });
                });

            modelBuilder.Entity("InvoiceAppAPI.Entity.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 101m,
                            CustomerId = 1,
                            Date = new DateTime(2023, 7, 9, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2727),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 102m,
                            CustomerId = 2,
                            Date = new DateTime(2023, 7, 8, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2775),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 103m,
                            CustomerId = 3,
                            Date = new DateTime(2023, 7, 7, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2778),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 104m,
                            CustomerId = 4,
                            Date = new DateTime(2023, 7, 6, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2780),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 105m,
                            CustomerId = 5,
                            Date = new DateTime(2023, 7, 5, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2785),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 106m,
                            CustomerId = 6,
                            Date = new DateTime(2023, 7, 4, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2788),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 107m,
                            CustomerId = 7,
                            Date = new DateTime(2023, 7, 3, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2791),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 108m,
                            CustomerId = 8,
                            Date = new DateTime(2023, 7, 2, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2794),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 109m,
                            CustomerId = 9,
                            Date = new DateTime(2023, 7, 1, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2797),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 110m,
                            CustomerId = 10,
                            Date = new DateTime(2023, 6, 30, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2801),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 11,
                            Amount = 111m,
                            CustomerId = 11,
                            Date = new DateTime(2023, 6, 29, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2804),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 12,
                            Amount = 112m,
                            CustomerId = 12,
                            Date = new DateTime(2023, 6, 28, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2807),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 13,
                            Amount = 113m,
                            CustomerId = 13,
                            Date = new DateTime(2023, 6, 27, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2810),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 14,
                            Amount = 114m,
                            CustomerId = 14,
                            Date = new DateTime(2023, 6, 26, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2812),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 15,
                            Amount = 115m,
                            CustomerId = 15,
                            Date = new DateTime(2023, 6, 25, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2815),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 16,
                            Amount = 116m,
                            CustomerId = 16,
                            Date = new DateTime(2023, 6, 24, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2818),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 17,
                            Amount = 117m,
                            CustomerId = 17,
                            Date = new DateTime(2023, 6, 23, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2821),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 18,
                            Amount = 118m,
                            CustomerId = 18,
                            Date = new DateTime(2023, 6, 22, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2825),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 19,
                            Amount = 119m,
                            CustomerId = 19,
                            Date = new DateTime(2023, 6, 21, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2828),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 20,
                            Amount = 120m,
                            CustomerId = 20,
                            Date = new DateTime(2023, 6, 20, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2830),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 21,
                            Amount = 121m,
                            CustomerId = 21,
                            Date = new DateTime(2023, 6, 19, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2833),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 22,
                            Amount = 122m,
                            CustomerId = 22,
                            Date = new DateTime(2023, 6, 18, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2835),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 23,
                            Amount = 123m,
                            CustomerId = 23,
                            Date = new DateTime(2023, 6, 17, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2838),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 24,
                            Amount = 124m,
                            CustomerId = 24,
                            Date = new DateTime(2023, 6, 16, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2841),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 25,
                            Amount = 125m,
                            CustomerId = 25,
                            Date = new DateTime(2023, 6, 15, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2843),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 26,
                            Amount = 126m,
                            CustomerId = 26,
                            Date = new DateTime(2023, 6, 14, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2846),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 27,
                            Amount = 127m,
                            CustomerId = 27,
                            Date = new DateTime(2023, 6, 13, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2849),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 28,
                            Amount = 128m,
                            CustomerId = 28,
                            Date = new DateTime(2023, 6, 12, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2852),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 29,
                            Amount = 129m,
                            CustomerId = 29,
                            Date = new DateTime(2023, 6, 11, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2905),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 30,
                            Amount = 130m,
                            CustomerId = 30,
                            Date = new DateTime(2023, 6, 10, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2908),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 31,
                            Amount = 131m,
                            CustomerId = 31,
                            Date = new DateTime(2023, 6, 9, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2911),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 32,
                            Amount = 132m,
                            CustomerId = 32,
                            Date = new DateTime(2023, 6, 8, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2914),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 33,
                            Amount = 133m,
                            CustomerId = 33,
                            Date = new DateTime(2023, 6, 7, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2917),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 34,
                            Amount = 134m,
                            CustomerId = 34,
                            Date = new DateTime(2023, 6, 6, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2921),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 35,
                            Amount = 135m,
                            CustomerId = 35,
                            Date = new DateTime(2023, 6, 5, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2924),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 36,
                            Amount = 136m,
                            CustomerId = 36,
                            Date = new DateTime(2023, 6, 4, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2927),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 37,
                            Amount = 137m,
                            CustomerId = 37,
                            Date = new DateTime(2023, 6, 3, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2929),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 38,
                            Amount = 138m,
                            CustomerId = 38,
                            Date = new DateTime(2023, 6, 2, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2932),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 39,
                            Amount = 139m,
                            CustomerId = 39,
                            Date = new DateTime(2023, 6, 1, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2935),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 40,
                            Amount = 140m,
                            CustomerId = 40,
                            Date = new DateTime(2023, 5, 31, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2937),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 41,
                            Amount = 141m,
                            CustomerId = 41,
                            Date = new DateTime(2023, 5, 30, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2940),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 42,
                            Amount = 142m,
                            CustomerId = 42,
                            Date = new DateTime(2023, 5, 29, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2943),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 43,
                            Amount = 143m,
                            CustomerId = 43,
                            Date = new DateTime(2023, 5, 28, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2946),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 44,
                            Amount = 144m,
                            CustomerId = 44,
                            Date = new DateTime(2023, 5, 27, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2948),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 45,
                            Amount = 145m,
                            CustomerId = 45,
                            Date = new DateTime(2023, 5, 26, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2951),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 46,
                            Amount = 146m,
                            CustomerId = 46,
                            Date = new DateTime(2023, 5, 25, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2954),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 47,
                            Amount = 147m,
                            CustomerId = 47,
                            Date = new DateTime(2023, 5, 24, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2956),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 48,
                            Amount = 148m,
                            CustomerId = 48,
                            Date = new DateTime(2023, 5, 23, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2959),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 49,
                            Amount = 149m,
                            CustomerId = 49,
                            Date = new DateTime(2023, 5, 22, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2962),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 50,
                            Amount = 150m,
                            CustomerId = 50,
                            Date = new DateTime(2023, 5, 21, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2964),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 51,
                            Amount = 151m,
                            CustomerId = 51,
                            Date = new DateTime(2023, 5, 20, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2967),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 52,
                            Amount = 152m,
                            CustomerId = 52,
                            Date = new DateTime(2023, 5, 19, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2970),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 53,
                            Amount = 153m,
                            CustomerId = 53,
                            Date = new DateTime(2023, 5, 18, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2973),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 54,
                            Amount = 154m,
                            CustomerId = 54,
                            Date = new DateTime(2023, 5, 17, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2975),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 55,
                            Amount = 155m,
                            CustomerId = 55,
                            Date = new DateTime(2023, 5, 16, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2978),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 56,
                            Amount = 156m,
                            CustomerId = 56,
                            Date = new DateTime(2023, 5, 15, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2981),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 57,
                            Amount = 157m,
                            CustomerId = 57,
                            Date = new DateTime(2023, 5, 14, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2983),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 58,
                            Amount = 158m,
                            CustomerId = 58,
                            Date = new DateTime(2023, 5, 13, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2986),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 59,
                            Amount = 159m,
                            CustomerId = 59,
                            Date = new DateTime(2023, 5, 12, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2989),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 60,
                            Amount = 160m,
                            CustomerId = 60,
                            Date = new DateTime(2023, 5, 11, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2991),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 61,
                            Amount = 161m,
                            CustomerId = 61,
                            Date = new DateTime(2023, 5, 10, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2994),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 62,
                            Amount = 162m,
                            CustomerId = 62,
                            Date = new DateTime(2023, 5, 9, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2997),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 63,
                            Amount = 163m,
                            CustomerId = 63,
                            Date = new DateTime(2023, 5, 8, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(2999),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 64,
                            Amount = 164m,
                            CustomerId = 64,
                            Date = new DateTime(2023, 5, 7, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3028),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 65,
                            Amount = 165m,
                            CustomerId = 65,
                            Date = new DateTime(2023, 5, 6, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3032),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 66,
                            Amount = 166m,
                            CustomerId = 66,
                            Date = new DateTime(2023, 5, 5, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3036),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 67,
                            Amount = 167m,
                            CustomerId = 67,
                            Date = new DateTime(2023, 5, 4, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3038),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 68,
                            Amount = 168m,
                            CustomerId = 68,
                            Date = new DateTime(2023, 5, 3, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3041),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 69,
                            Amount = 169m,
                            CustomerId = 69,
                            Date = new DateTime(2023, 5, 2, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3044),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 70,
                            Amount = 170m,
                            CustomerId = 70,
                            Date = new DateTime(2023, 5, 1, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3046),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 71,
                            Amount = 171m,
                            CustomerId = 71,
                            Date = new DateTime(2023, 4, 30, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3049),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 72,
                            Amount = 172m,
                            CustomerId = 72,
                            Date = new DateTime(2023, 4, 29, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3052),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 73,
                            Amount = 173m,
                            CustomerId = 73,
                            Date = new DateTime(2023, 4, 28, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3054),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 74,
                            Amount = 174m,
                            CustomerId = 74,
                            Date = new DateTime(2023, 4, 27, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3057),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 75,
                            Amount = 175m,
                            CustomerId = 75,
                            Date = new DateTime(2023, 4, 26, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3060),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 76,
                            Amount = 176m,
                            CustomerId = 76,
                            Date = new DateTime(2023, 4, 25, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3063),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 77,
                            Amount = 177m,
                            CustomerId = 77,
                            Date = new DateTime(2023, 4, 24, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3065),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 78,
                            Amount = 178m,
                            CustomerId = 78,
                            Date = new DateTime(2023, 4, 23, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3068),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 79,
                            Amount = 179m,
                            CustomerId = 79,
                            Date = new DateTime(2023, 4, 22, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3071),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 80,
                            Amount = 180m,
                            CustomerId = 80,
                            Date = new DateTime(2023, 4, 21, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3073),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 81,
                            Amount = 181m,
                            CustomerId = 81,
                            Date = new DateTime(2023, 4, 20, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3076),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 82,
                            Amount = 182m,
                            CustomerId = 82,
                            Date = new DateTime(2023, 4, 19, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3078),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 83,
                            Amount = 183m,
                            CustomerId = 83,
                            Date = new DateTime(2023, 4, 18, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3081),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 84,
                            Amount = 184m,
                            CustomerId = 84,
                            Date = new DateTime(2023, 4, 17, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3084),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 85,
                            Amount = 185m,
                            CustomerId = 85,
                            Date = new DateTime(2023, 4, 16, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3087),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 86,
                            Amount = 186m,
                            CustomerId = 86,
                            Date = new DateTime(2023, 4, 15, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3089),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 87,
                            Amount = 187m,
                            CustomerId = 87,
                            Date = new DateTime(2023, 4, 14, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3092),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 88,
                            Amount = 188m,
                            CustomerId = 88,
                            Date = new DateTime(2023, 4, 13, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3095),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 89,
                            Amount = 189m,
                            CustomerId = 89,
                            Date = new DateTime(2023, 4, 12, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3097),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 90,
                            Amount = 190m,
                            CustomerId = 90,
                            Date = new DateTime(2023, 4, 11, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3100),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 91,
                            Amount = 191m,
                            CustomerId = 91,
                            Date = new DateTime(2023, 4, 10, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3103),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 92,
                            Amount = 192m,
                            CustomerId = 92,
                            Date = new DateTime(2023, 4, 9, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3105),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 93,
                            Amount = 193m,
                            CustomerId = 93,
                            Date = new DateTime(2023, 4, 8, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3108),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 94,
                            Amount = 194m,
                            CustomerId = 94,
                            Date = new DateTime(2023, 4, 7, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3111),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 95,
                            Amount = 195m,
                            CustomerId = 95,
                            Date = new DateTime(2023, 4, 6, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3140),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 96,
                            Amount = 196m,
                            CustomerId = 96,
                            Date = new DateTime(2023, 4, 5, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3142),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 97,
                            Amount = 197m,
                            CustomerId = 97,
                            Date = new DateTime(2023, 4, 4, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3145),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 98,
                            Amount = 198m,
                            CustomerId = 98,
                            Date = new DateTime(2023, 4, 3, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3148),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 99,
                            Amount = 199m,
                            CustomerId = 99,
                            Date = new DateTime(2023, 4, 2, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3150),
                            Status = "Unpaid"
                        },
                        new
                        {
                            Id = 100,
                            Amount = 200m,
                            CustomerId = 100,
                            Date = new DateTime(2023, 4, 1, 21, 1, 41, 203, DateTimeKind.Local).AddTicks(3154),
                            Status = "Paid"
                        });
                });

            modelBuilder.Entity("InvoiceAppAPI.Entity.Invoice", b =>
                {
                    b.HasOne("InvoiceAppAPI.Models.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("InvoiceAppAPI.Models.Customer", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
