/*
 * MinhalTest API
 *
 * API providing data for MinhalTest
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: tompha1@hotmail.co.il
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;


namespace InvoiceAppAPI.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class SearchTemplate
    {            
        public int PageNumber { get; set; }       
        
        public int PageSize { get; set; }      
       
        public string? OrderByField { get; set; }      
        
        public string? Sort { get; set; }        
        
        public string? SearchKey { get; set; }        
                
    }
}
